# Book settings
# For your DS implementation, you will need to update author, repository:url:, and html:baseurl:

# Learn more at https://jupyterbook.org/customize/config.html
title: Documentation
author: Broad Institute
copyright: "2022"
#logo: img/logo.svg

# Only build files that are in the ToC
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
#latex:
#  latex_documents:
#    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/distributed-something/documentation
  branch: main  # Which branch of the repository should be used when creating links (optional)
  path_to_book: DS-documentation

html:
  #favicon: "img/favicon.ico"
  baseurl: distributed-something.github.io
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  comments:
    hypothesis: true

parse:
  myst_enable_extensions:
    # Only required if you use html <img>
    - html_image
